<div id="search-block">
	<div class="wrapper">
		<div class="search-block clearfix">
			<form action="/job/search/searchform" method="get">
				<input name="q" class="width-80" id="keyword"
					value="<?php echo $this->getKeyword();?>"
					placeholder="<?php echo $this->__('検索キーワードはこちらに入力してください。') ?>" />
				<br class="clear"/>
				<select name="location" class="inline">
					<option value=""><?php echo $this->__('国から探す') ?></option>
					<?php echo $this->getLocationList() ?>
				</select>
				
				<select name="category" class="inline">
					<option value=""><?php echo $this->__('業界・職種から探す') ?></option>
					<?php echo $this->getCategoryList() ?>
				</select>
				
				<select name="language" class="inline">
					<option value=""><?php echo $this->__('言語から探す') ?></option>
					<?php echo $this->getLanguageList() ?>			
				</select>
				
				<button id="search-btn" name"submit" type="submit" class="flr inline btn btn-orange"><?php echo $this->__('検索する') ?></button>		
			</form>
		</div>
	</div>
</div>