<div class="register-top">
	<h1><?php echo $this->__('ご登録、ありがとうございました！') ?></h1>
	
	<p><?php echo $this->__('アイコニックへの会員登録が完了しました。') ?></p>
	<p><?php echo $this->__('弊社<a href="%s">ホームページ</a>から、%s様のご要望に叶う求人を検索してみてくださいね！', Mage::helper('job')->getBaseUrl() ,Mage::getSingleton('customer/session')->getCustomer()->getFirstname()) ?></p>
</div>
<div class="success-page-blue register blue">
	<div class="normal text">
		<?php echo $this->__('アジア転職のプロと直接お話しませんか？<br />%s様のご経歴を簡単にご登録頂ければ、アジア転職に精通したアイコニックのコンサルタントが求人情報から生活情報まで、どんなお悩みにもお答えします！',Mage::getSingleton('customer/session')->getCustomer()->getFirstname()) ?>
	</div>
	<div class="button">
		<a href="<?php echo Mage::helper('job')->getBaseUrl().Mage::helper('job')->getCreateCVUrl() ?>" class="btn">
			<?php echo $this->__('転職支援サービスに申し込む （無料）') ?>
		</a>
		<p><?php echo $this->__('(約3分で完了します）') ?></p>
	</div>
</div>
<style>
	h1{
		color: #d76f2c;
		font-weight: bold;
		margin-top: 20px;
	}
	#main .main{
		background: transparent;
		border: none;
	}
	.register-top p{
		text-align: center;
	}
</style>