<div class="success-page register">
	<h1><?php echo $this->__('おめでとうございます !!!') ?></h1>
	
	<p><?php echo $this->__('ICONIC－JPへの登録完了致しました。メールをご確認の後、手順の通りご活用ください。') ?></p>
	<p><?php echo $this->__('>> アクティベーションメールを拒否設定の場合は要領をご確認下さい/スパムフォルダー<br />>> 何か問題の場合はご<a href="%s">連絡下さい。</a>', Mage::helper('job')->getBaseUrl().Mage::helper('job')->getContactUrl()) ?></p>
</div>
<style>
	.success-page.register{
		width: 550px;
		margin: auto;
		padding: 20px;
	}
	#main .main{
		background-color: transparent;
		border: none;
	}
	.success-page h1{
		color: #d76f2c;
		text-align: center;
		font-weight: bold;
		font-size: 23px;
		margin-bottom: 25px;
	}
	.success-page p{
		font-size: 13px;
	}
</style>
