<div class="register-top">
	<h1><?php echo $this->__('ご登録、ありがとうございました！') ?></h1>
	
	<p><?php echo $this->__('アイコニックへの会員登録が完了しました。') ?></p>
	<p><?php echo $this->__('弊社<a href="%s">ホームページ</a>から、%s様のご要望に叶う求人を検索してみてくださいね！', Mage::helper('job')->getBaseUrl() ,Mage::getSingleton('customer/session')->getCustomer()->getFirstname()) ?></p>
</div>
<div class="success-page-blue register blue">
	<div class="normal text">
		<?php echo $this->__('アジア転職のプロと直接お話しませんか？<br />%s様のご経歴を簡単にご登録頂ければ、アジア転職に精通したアイコニックのコンサルタントが求人情報から生活情報まで、どんなお悩みにもお答えします！',Mage::getSingleton('customer/session')->getCustomer()->getFirstname()) ?>
	</div>
	<div class="button">
		<a href="<?php echo Mage::helper('job')->getBaseUrl().Mage::helper('job')->getCreateCVUrl() ?>" class="btn">
			<?php echo $this->__('転職支援サービスに申し込む （無料）') ?>
		</a>
		<p><?php echo $this->__('(約3分で完了します）') ?></p>
	</div>
</div>
<style>
	h1{
		color: #d76f2c;
		font-weight: bold;
		margin-top: 20px;
	}
	#main .main{
		background: transparent;
		border: none;
	}
	.register-top p{
		text-align: center;
	}
</style>
<!-- Google Code for Sign-up Conversion Page --> 
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 964610057;
var google_conversion_language = "en";
var google_conversion_format = "3";
var google_conversion_color = "ffffff";
var google_conversion_label = "J2StCJfosgkQiZD7ywM"; var google_remarketing_only = false;
/* ]]> */
</script>
<script type="text/javascript"  
src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt=""  
src="//www.googleadservices.com/pagead/conversion/964610057/?label=J2StCJfosgkQiZD7ywM&amp;guid=ON&amp;script=0"/>
</div>
</noscript>