<?php $items = $this->getLatestNewsItems() ?>
<?php if (count($items)): ?>
<div class="block news-categories">
    <div class="block-content">
        <div class="menu-categories">
            <ul>
                <?php foreach ($items as $item): ?>
                	<?php if ($item->getData('status') == 1):?>
                    <li class="clearfix">
                        <div class="item-content">
	                        <a title="<?php echo $item->getTitle() ?>" class="width-100" href="<?php echo str_replace('clnews', $this->getAlias(), $item->getUrl()) ?>" >
	                        	<div class="date">
	                        		<?php echo Mage::helper('job')->formatDate($item->getNewsTime()) ?>
	                        	</div>
	                        	<div class="tit">
	                        		<?php echo Mage::helper('job')->limitText(strip_tags($item->getTitle())) ?>
	                        	</div>
		                        <div class="short-desc width-100">
		                        	<?php echo Mage::helper('job')->string_limit_words(strip_tags($item->getShortContent())) ?>
		                        </div>
	                        </a>
	                	</div>
                    <?php endif; ?>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
</div>
<?php endif; ?>
