<div class="success-page createcv">
	<h3><?php echo $this->__('Congratulations!') ?></h3>
	
	<p>You have successfully created your resume at iconic-jp.com</a></p>
	<p>Our Iconic staff will review your resume and introduce suitable jobs to you.</p>
	<br />
	<p>Automatically come back to Homepage after <span id="countdown">5</span>s.</p>
</div>

<script type="text/javascript">
	(function () {
	    var timeLeft = 5,
	        cinterval;
	
	    var timeDec = function (){
	        timeLeft--;
	        document.getElementById('countdown').innerHTML = timeLeft;
	        if(timeLeft === 0){
	        	window.location = '/';
	            clearInterval(cinterval);
	        }
	    };
	
	    cinterval = setInterval(timeDec, 1000);
	})();
</script>
