<div class="success-page createcv">
	<h3><?php echo $this->__('お申込み、有難うございました！') ?></h3>
	<p><?php echo $this->__('転職支援サービスへのお申込みが完了しました。') ?></p>
	<br />
	<p><?php echo $this->__('アジア転職のプロであるアイコニックのキャリアアドバイザーから、<br />一両日中に、面談日程調整のための連絡を入れさせて頂きます。') ?></p>
	<br />
	<p><?php echo $this->__('%sさんのアジア転職が成功するように、一緒にがんばりましょう！', Mage::getSingleton('customer/session')->getCustomer()->getFirstname()) ?></p>
	<br />
	<p><?php echo $this->__('このページは<span id="countdown">5</span>秒後に自動的にホームページへ切り替わります。') ?></p>
</div>

<script type="text/javascript">
	(function () {
	    var timeLeft = 5,
	        cinterval;
	
	    var timeDec = function (){
	        timeLeft--;
	        document.getElementById('countdown').innerHTML = timeLeft;
	        if(timeLeft === 0){
	        	window.location = '/';
	            clearInterval(cinterval);
	        }
	    };
	
	    cinterval = setInterval(timeDec, 1000);
	})();
</script>
<!-- Google Code for Sign-up Conversion Page --> 
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 964610057;
var google_conversion_language = "en";
var google_conversion_format = "3";
var google_conversion_color = "ffffff";
var google_conversion_label = "J2StCJfosgkQiZD7ywM"; var google_remarketing_only = false;
/* ]]> */
</script>
<script type="text/javascript"  
src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt=""  
src="//www.googleadservices.com/pagead/conversion/964610057/?label=J2StCJfosgkQiZD7ywM&amp;guid=ON&amp;script=0"/>
</div>
</noscript>