<?php $job = $this->getItem() ?>
<?php $jobs = $this->getJobsInCategory() ?>
<div class
<div id="page-title">
	<h2 class="blue-tit text-blue">
		<?php echo $this->__('応募完了') ?>
	</h2>
</div>
<div class="greetings">
	<h3 class="iconic-id">
		<?php echo $this->__('<b>No. %s</b>   |   登録日: %s', $job->getIconicId(), Mage::helper('job')->formatDate($job->getCreatedTime())) ?>
	</h3>
	<h1>
		<?php echo $job->getTitle() ?>
	</h1>
	<div class="apply-success-message clearfix">
		<div class="message">
			<p class="success text-orange"><?php echo $this->__('ご応募が完了しました！') ?></p>
			<p><?php echo $this->__('ご応募、有難うございました。応募状況の進捗があり次第、弊社コンサルタントより連絡を入れさせて頂きます。ご質問等ございましたら、御気軽に<a href="/%s">こちら</a>からお問い合わせください。', Mage::helper('job')->getContactUrl()) ?></p>
		</div>
	</div>
</div>

<!-- Jobs Same Category -->
<?php if(count($jobs) > 0): ?>
<div id="job-same-category">
	<fieldset>
		<legend class="text-blue">
			<?php echo $this->__('同じカテゴリーのお仕事をチェックする！') ?>
		</legend>
		<ul class="jobs-list">
		
			<?php foreach($jobs as $jb): ?>
				<li>
					<p class="iconic-id">
						<?php echo $this->__('<b>No. %s</b>   |   登録日: %s', $jb->getIconicId(), Mage::helper('job')->formatDate($jb->getCreatedTime())) ?>
					</p>
					<p class="title">
						<?php if($this->getKeyword()): ?>
							<?php echo Mage::helper('job')->highlight($jb->getTitle(), explode(' ',$this->getKeyword())) ?>
						<?php else: ?>
							<?php echo $jb->getTitle() ?>
						<?php endif; ?>
					</p>
					<div class="job-details">
						<table>
							<tr>
								<td class="tit"><?php echo $this->__('国') ?>:</td><td><?php echo $jb->getCountry() ?></td>
								<td class="tit"><?php echo $this->__('勤務地') ?>:</td><td><?php echo $jb->getWorkLocation() ?></td>
								<td class="tit"><?php echo $this->__('言語') ?>:</td><td><?php echo $jb->getLanguage() ?></td>
								<td class="tit"><?php echo $this->__('給与') ?>:</td><td><?php echo $jb->getFullSalary() ?></td>
							</tr>
							<tr>
								<td class="tit"><?php echo $this->__('業種') ?>:</td><td><?php echo $jb->getCategoryName() ?></td>
								<td class="tit"><?php echo $this->__('職種') ?>:</td><td><?php echo $jb->getFunctionName() ?></td>
								<td class="tit"><?php echo $this->__('レベル ') ?>:</td><td><?php echo $jb->getLevel() ?></td>
								<td class="tit"><?php echo $this->__('採用定数') ?>:</td><td><?php echo $jb->getAmount() ?></td>
							</tr>
						</table>
					</div>
					<div class="actions">
						<a class="view" href="<?php echo $jb->getUrl() ?>"><?php echo $this->__('詳細を見る') ?></a>
						<a class="apply" href="<?php echo $jb->getApplyUrl() ?>"><?php echo $this->__('応募する') ?></a>
					</div>
				</li>
			<?php endforeach; ?>
		</ul>
		<a class="text-blue view-more-category" href="<?php echo Mage::helper('job')->getCategoryUrl($job->getCategoryId()); ?>">>> <?php echo $this->__('もっと見る') ?></a>
	</fieldset>
</div>
<?php endif; ?>