<div id="contact-page" class="clearfix">
	<div class="fll">
		<h1 class="blue-tit"><?php echo $this->__('問い合わせる') ?></h1>
		<p><?php echo $this->__('ご不明、ご質問等ありましたらこちらでお答え致します。') ?></p>
		<p><?php echo $this->__('ご連絡頂けましたら早急にお答え致します。') ?></p>
		<form action="" method="post" id="contact-form">
			<div class="row clearfix">
				<input class="fll" required name="name" type="text" placeholder="<?php echo $this->__('氏名') ?>" />
				<input class="flr" required name="email" type="email" placeholder="<?php echo $this->__('電子メール') ?>" />
			</div>
			
			<div class="row clearfix">
				<input class="fll" name="companyname" type="text" placeholder="<?php echo $this->__('会社名') ?>" />
				<input class="flr" name="phone" type="number" placeholder="<?php echo $this->__('電話番号') ?>" />
			</div>
			
			<div class="row">
				<textarea required name="message" placeholder="<?php echo $this->__('メッセージ') ?>"></textarea>
			</div>
			
			<div class="actions">
				<button type="submit" class="button-blue btn"><?php echo $this->__('送信') ?></button>
				<button onclick="resetForm();" class="button-grey btn"><?php echo $this->__('取消') ?></button>
			</div>
		</form>
	</div>
	
	<div class="flr">
		<div class="row">
			<p class="tit"><?php echo $this->__('ウェブ') ?>:</p>
			<a href="mailto:info@iconic-jp.com">info@iconic-jp.com</a>
		</div>
		<div class="row">
			<p class="tit"><?php echo $this->__('電話') ?>:</p>
			<p><?php echo $this->__('ベトナム - 南部') ?></p>
			<p>(84) - 8 - 3821 5122 / 5123 / 5124</p>
		</div>
		<div class="row">
			<p><?php echo $this->__('ベトナム - 北部') ?></p>
			<p>84 - 4 - 3776 / 5963</p>
		</div>
		<div class="row">
			<p><?php echo $this->__('東京 - 日本') ?></p>
			<p>(81) - 3 - 6222 5520</p>
		</div>
		<div class="row">
			<p><?php echo $this->__('インドネシア') ?></p>
			<p>(62) - 21 290 22273</p>
			<p>(62) - 21 290 22274</p>
		</div>
	</div>
</div>