<?php $data = $this->getFormData(); ?>
<div class="create-cv">
    <div class="page-title">
        <h1><?php echo $this->__('転職支援サービスに申し込む<br />（アイコニック求職登録）') ?></h1>
    </div>
    <form action="/<?php echo Mage::helper('job')->getCreateCVUrl() ?>" method="post" id="form-validate">
    	<input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
    	<div class="row">
    		<?php echo $this->__('＊＝必須') ?>
    	</div>
    	<div class="row heading">
    		<?php echo $this->__('プロフィール') ?>
    	</div>
    	
    	<div class="row row2">
    		<input required class="first after-input" type="text" name="first" placeholder="<?php echo $this->__('姓') ?>" value="<?php echo $this->getCustomer()->getFirstname() ?>" />
    		<input required class="last after-input" type="text" name="last" placeholder="<?php echo $this->__('名') ?>" value="<?php echo $this->getCustomer()->getLastname() ?>" />
    	</div>
    	
    	<div class="row row2">
    		<?php $kana = explode(' ',$this->getCustomer()->getKana()) ?>
    		<input class="first <?php echo ($kana[0]) ? 'after-input' : '' ?>" name="kanafirst" placeholder="<?php echo $this->__('性（フリガナ）') ?>" value="<?php echo $kana[0] ?>" />
    		<input class="last <?php echo ($kana[1]) ? 'after-input' : '' ?>" name="kanalast" placeholder="<?php echo $this->__('名（フリガナ）') ?>" value="<?php echo $kana[1] ?>" /> 
    	</div>
    	
    	<div class="row row2">
    		<div class="first div3">
    			<?php $birthday = explode('/',$this->getCustomer()->getBirthYear()); ?>
    			<select name="year" class="first fll after-input">
    				<?php 
                	$y = (int) Date('Y');
                	for($i = $y-10; $i >= $y-60;$i--): ?>
                	<option <?php echo ($birthday[0]==$i) ? 'selected="selected"' : '' ?> value="<?php echo $i ?>"><?php echo $i ?></option>
                	<?php endfor; ?>
    			</select>
    			<select name="month" class="middle after-input">
    					<option value=""><?php echo $this->__('生月') ?></option>
		            	<?php 
		            	for($i = 1; $i <= 12;$i++): ?>
		            	<option <?php echo ($birthday[1]==$i) ? 'selected="selected"' : '' ?> value="<?php echo $i ?>"><?php echo $i ?></option>
		            	<?php endfor; ?>
    			</select>
    			<select name="day" class="last flr after-input">
    				<option value=""><?php echo $this->__('生日') ?></option>
	            	<?php 
	            	for($i = 1; $i <= 31;$i++): ?>
	            	<option <?php echo ($birthday[2]==$i) ? 'selected="selected"' : '' ?> value="<?php echo $i ?>"><?php echo $i ?></option>
	            	<?php endfor; ?>
    			</select>
    		</div>
    		
    		<select required class="last after-input" name="sex" placeholder="<?php echo $this->__('性別') ?>" value="<?php echo $this->getCustomer()->getSex() ?>">
    			<option value=""><?php echo $this->__('性別') ?></option>
            	<option <?php echo ($this->getCustomer()->getSex()=='男性') ? 'selected="selected"' : '' ?> value="<?php echo 1 ?>"><?php echo $this->__('男性') ?></option>
            	<option <?php echo ($this->getCustomer()->getSex()=='女性') ? 'selected="selected"' : '' ?> value="<?php echo 2 ?>"><?php echo $this->__('女性') ?></option>
    		</select>
    	</div>
    	
    	<div class="row row2 clearfix">
    		<select name="nation" id="nation" class="first">
    			<option value=""><?php echo $this->__('国籍') ?></option>
    			<?php $list = Mage::getModel('job/listlocation')->getCollection() ?>
    			<?php foreach($list as $loc): ?>
    			<option value="<?php echo $loc->getName() ?>"><?php echo Mage::helper('job')->getTransName($loc) ?></option>
    			<?php endforeach; ?>
    		</select>
		    <select name="country" class="last after-input">	
	    		<option value=""><?php echo $this->__('現在住んでいる国') ?></option>
				<?php $countries = Mage::getModel('job/listlocation')->getCollection() ?>
				<?php foreach($countries as $country): ?>
					<option <?php echo ($this->getCustomer()->getLocation()==$country->getId()) ? 'selected="selected"' : '' ?> value="<?php echo $country->getName() ?>"><?php echo $country->getName() ?></option>
				<?php endforeach; ?>
    		</select>
    	</div>
    	
    	<div class="row row2">
    		<select class="first" name="province">
    			  <option value=""><?php echo $this->__('都道府県') ?></option>
    			  <option value="<?php echo $this->__('北海道') ?>"><?php echo $this->__('北海道') ?></option>
    			  <option value="<?php echo $this->__('青森県') ?>"><?php echo $this->__('青森県') ?></option>
    			  <option value="<?php echo $this->__('岩手県') ?>"><?php echo $this->__('岩手県') ?></option>
    			  <option value="<?php echo $this->__('宮城県') ?>"><?php echo $this->__('宮城県') ?></option>
    			  <option value="<?php echo $this->__('秋田県') ?>"><?php echo $this->__('秋田県') ?></option>
    			  <option value="<?php echo $this->__('山形県') ?>"><?php echo $this->__('山形県') ?></option>
    			  <option value="<?php echo $this->__('福島県') ?>"><?php echo $this->__('福島県') ?></option>
    			  <option value="<?php echo $this->__('茨城県') ?>"><?php echo $this->__('茨城県') ?></option>
    			  <option value="<?php echo $this->__('栃木県') ?>"><?php echo $this->__('栃木県') ?></option>
    			  <option value="<?php echo $this->__('群馬県') ?>"><?php echo $this->__('群馬県') ?></option>
    			  <option value="<?php echo $this->__('埼玉県') ?>"><?php echo $this->__('埼玉県') ?></option>
    			  <option value="<?php echo $this->__('千葉県') ?>"><?php echo $this->__('千葉県') ?></option>
    			  <option value="<?php echo $this->__('東京都') ?>"><?php echo $this->__('東京都') ?></option>
    			  <option value="<?php echo $this->__('神奈川県') ?>"><?php echo $this->__('神奈川県') ?></option>
    			  <option value="<?php echo $this->__('山梨県') ?>"><?php echo $this->__('山梨県') ?></option>
    			  <option value="<?php echo $this->__('新潟県') ?>"><?php echo $this->__('新潟県') ?></option>
    			  <option value="<?php echo $this->__('富山県') ?>"><?php echo $this->__('富山県') ?></option>
    			  <option value="<?php echo $this->__('石川県') ?>"><?php echo $this->__('石川県') ?></option>
    			  <option value="<?php echo $this->__('福井県') ?>"><?php echo $this->__('福井県') ?></option>
    			  <option value="<?php echo $this->__('長野県') ?>"><?php echo $this->__('長野県') ?></option>
    			  <option value="<?php echo $this->__('岐阜県') ?>"><?php echo $this->__('岐阜県') ?></option>
    			  <option value="<?php echo $this->__('静岡県') ?>"><?php echo $this->__('静岡県') ?></option>
    			  <option value="<?php echo $this->__('愛知県') ?>"><?php echo $this->__('愛知県') ?></option>
    			  <option value="<?php echo $this->__('三重県') ?>"><?php echo $this->__('三重県') ?></option>
    			  <option value="<?php echo $this->__('滋賀県') ?>"><?php echo $this->__('滋賀県') ?></option>
    			  <option value="<?php echo $this->__('京都府') ?>"><?php echo $this->__('京都府') ?></option>
    			  <option value="<?php echo $this->__('大阪府') ?>"><?php echo $this->__('大阪府') ?></option>
    			  <option value="<?php echo $this->__('奈良県') ?>"><?php echo $this->__('奈良県') ?></option>
    			  <option value="<?php echo $this->__('和歌山県') ?>"><?php echo $this->__('和歌山県') ?></option>
    			  <option value="<?php echo $this->__('兵庫県') ?>"><?php echo $this->__('兵庫県') ?></option>
    			  <option value="<?php echo $this->__('鳥取県') ?>"><?php echo $this->__('鳥取県') ?></option>
    			  <option value="<?php echo $this->__('島根県') ?>"><?php echo $this->__('島根県') ?></option>
    			  <option value="<?php echo $this->__('岡山県') ?>"><?php echo $this->__('岡山県') ?></option>
    			  <option value="<?php echo $this->__('広島県') ?>"><?php echo $this->__('広島県') ?></option>
    			  <option value="<?php echo $this->__('山口県') ?>"><?php echo $this->__('山口県') ?></option>
    			  <option value="<?php echo $this->__('徳島県') ?>"><?php echo $this->__('徳島県') ?></option>
    			  <option value="<?php echo $this->__('香川県') ?>"><?php echo $this->__('香川県') ?></option>
    			  <option value="<?php echo $this->__('愛媛県') ?>"><?php echo $this->__('愛媛県') ?></option>
    			  <option value="<?php echo $this->__('高知県') ?>"><?php echo $this->__('高知県') ?></option>
    			  <option value="<?php echo $this->__('福岡県') ?>"><?php echo $this->__('福岡県') ?></option>
    			  <option value="<?php echo $this->__('佐賀県') ?>"><?php echo $this->__('佐賀県') ?></option>
    			  <option value="<?php echo $this->__('長崎県') ?>"><?php echo $this->__('長崎県') ?></option>
    			  <option value="<?php echo $this->__('熊本県') ?>"><?php echo $this->__('熊本県') ?></option>
    			  <option value="<?php echo $this->__('大分県') ?>"><?php echo $this->__('大分県') ?></option>
    			  <option value="<?php echo $this->__('宮崎県') ?>"><?php echo $this->__('宮崎県') ?></option>
    			  <option value="<?php echo $this->__('鹿児島県') ?>"><?php echo $this->__('鹿児島県') ?></option>
    			  <option value="<?php echo $this->__('沖縄県') ?>"><?php echo $this->__('沖縄県') ?></option>
    		</select>
    		
    		<input required class="last" name="location" placeholder="<?php echo $this->__('住所詳細') ?>" />
    	</div>
    	
    	<div class="row row2">
    		<div class="first div3">
    			<input class="first" type="number" name="phone1" placeholder="<?php echo $this->__('電話番号') ?>" />
    			<span>-</span>
    			<input type="number" name="phone2" />
    			<span>-</span>
    			<input type="number" name="phone3" class="last" />
    		</div>
    		<input readonly required type="email" class="last after-input" name="email" id="email" placeholder="Email*" value="<?php echo $this->getCustomer()->getEmail() ?>" />
    	</div>
    	
    	<div class="row heading">
    		<?php echo $this->__('学歴') ?>
    	</div>
    	
    	<div class="row degree">
    		<select id="degree" class="" required name="degree">
    			<option value=""><?php echo $this->__('最終学歴') ?></option>
    			<option value="<?php echo $this->__('大学院') ?>"><?php echo $this->__('大学院') ?></option>
    			<option value="<?php echo $this->__('4年制大学') ?>"><?php echo $this->__('4年制大学') ?></option>
    			<option value="<?php echo $this->__('短期大学') ?>"><?php echo $this->__('短期大学') ?></option>
    			<option value="<?php echo $this->__('高等専門学校') ?>"><?php echo $this->__('高等専門学校') ?></option>
    			<option value="<?php echo $this->__('専門学校') ?>"><?php echo $this->__('専門学校') ?></option>
    			<option value="<?php echo $this->__('高校') ?>"><?php echo $this->__('高校') ?></option>
    			<option value="<?php echo $this->__('中学校') ?>"><?php echo $this->__('中学校') ?></option>
    		</select>
    		<input required type="radio" name="graduated" value="卒業" /><?php echo $this->__('卒業') ?>
    		<input type="radio" name="graduated" value="中退" /><?php echo $this->__('中退') ?>
    	</div>
    	
    	<div class="row row2">
    		<input required class="first" type="text" name="major" placeholder="<?php echo $this->__('学校名') ?>" />
    		<input class="last" type="text" name="school" placeholder="<?php echo $this->__('学部・学科名') ?>" />
    	</div>
    	
    	<div class="row heading">
    		<?php echo $this->__('職歴') ?>
    	</div>
    	
    	<div class="row work-status">
    		<?php echo $this->__(' 就業状況') ?><span class="red"></span>
    		<input id="check-for-working" required name="workstatus" type="radio" value="就業中" /><?php echo $this->__('就業中') ?>
    		<input name="workstatus" type="radio" value="離職済み" /><?php echo $this->__('離職済み') ?>
    	</div>
    	
    	<div class="row row2">
    		<select id="numbercompany" required class="first" name="numbercompany">
    			<option value=""><?php echo $this->__('経験社数') ?></option>
    			<?php for($i=0;$i<21;$i++): ?>
    			<option value="<?php echo $i ?>"><?php echo $i; ?></option>
    			<?php endfor; ?>
    		</select>
    		
    		<select id="workfunction" multiple="multiple" class="last" required name="workfunction[]">
    			<option value=""><?php echo $this->__('経験職種') ?></option>
    			<?php echo $this->getFunctionList($data['workfunction']) ?>
    		</select>
    		<script>
    			jQuery('#workfunction').multipleSelect({
		            selectAll: false,
		            placeholder: '<?php echo $this->__('経験職種') ?>',
		        });
    		</script>
    	</div>
    	<p class="after-numbercompany"><?php echo $this->__('(※新卒の方、今回が初めての就職となる方は、こちらで「0」を選択してください.)') ?></p>
    	
    	<div class="row dashed-border"></div>
    	<div class="company">
	    	<div class="row row2">
	    		<input required class="first" type="text" name="companyname" placeholder="<?php echo $this->__('企業名') ?>" />
	    		<div class="last income">
		    		<input required type="number" name="companysalary" placeholder="<?php echo $this->__('月収') ?>" />
		    		<?php echo $this->__('万円') ?>
	    		</div>
	    	</div>
	    	
	    	<div class="row row2">
	    		<select multiple="multiple" id="companycategory" required class="first" name="companycategory[]">
					<option value=""><?php echo $this->__('業種') ?></option>
					<?php echo $this->getCategoryList($data['companycategory']) ?>			
	    		</select>
	    		<script>
	    			jQuery('#companycategory').multipleSelect({
			            selectAll: false,
			            placeholder: '<?php echo $this->__('業種') ?>',
			        });
	    		</script>
	    		<input class="last" type="text" name="companytitle" placeholder="<?php echo $this->__('役職名') ?>" />
	    	</div>
	    	
	    	<div class="row row2">
	    		<input class="first" type="text" name="division" placeholder="<?php echo $this->__('部署名') ?>" />
	    		<select class="last" required name="companystatus">
	    			<option value=""><?php echo $this->__('就業形態') ?></option>
	    			<option value="<?php echo $this->__('正社員') ?>"><?php echo $this->__('正社員') ?></option>
	    			<option value="<?php echo $this->__('契約社員') ?>"><?php echo $this->__('契約社員') ?></option>
	    			<option value="<?php echo $this->__('派遣社員') ?>"><?php echo $this->__('派遣社員') ?></option>
	    			<option value="<?php echo $this->__('アルバイト') ?>"><?php echo $this->__('アルバイト') ?></option>
	    			<option value="<?php echo $this->__('その他') ?>"><?php echo $this->__('その他') ?></option>
	    		</select>
	    	</div>
	    	
	    	<div class="row row2 workingtime">
	    		<input class="first" type="number" name="companyemploye" placeholder="<?php echo $this->__('従業員数') ?>" />
	    		<div class="last div4">
	    			<select class="first" required name="yearfrom">
	    				<option value=""><?php echo $this->__('年') ?></option>
	    				<?php 
	                	$y = (int) Date('Y');
	                	for($i = $y; $i >= $y-60;$i--): ?>
	                	<option <?php echo ($data['yearfrom']==$i) ? 'selected="selected"' : '' ?> value="<?php echo $i ?>"><?php echo $i ?></option>
	                	<?php endfor; ?>
	    			</select>
	    			<select required name="monthfrom">
	    				<option value=""><?php echo $this->__('月') ?></option>
	    				<?php 
		            	for($i = 1; $i <= 12;$i++): ?>
		            	<option <?php echo ($data['monthfrom']==$i) ? 'selected="selected"' : '' ?> value="<?php echo $i ?>"><?php echo $i ?></option>
		            	<?php endfor; ?>
	    			</select>
	    			<span>-</span>
	    			<select name="yearto" class="need-disable">
	    				<option value=""><?php echo $this->__('年') ?></option>
	    				<?php 
	                	$y = (int) Date('Y');
	                	for($i = $y; $i >= $y-60;$i--): ?>
	                	<option <?php echo ($data['yearto']==$i) ? 'selected="selected"' : '' ?> value="<?php echo $i ?>"><?php echo $i ?></option>
	                	<?php endfor; ?>
	    			</select>
	    			<select class="last need-disable" name="monthto">
	    				<option value=""><?php echo $this->__('月') ?></option>
	    				<?php 
		            	for($i = 1; $i <= 12;$i++): ?>
		            	<option <?php echo ($data['monthto']==$i) ? 'selected="selected"' : '' ?> value="<?php echo $i ?>"><?php echo $i ?></option>
		            	<?php endfor; ?>
	    			</select>
	    		</div>
	    		<p class="small"><?php echo $this->__('（※現在、就業中の方は、就業開始時期のみ入力してください。）') ?></p>
	    	</div>
	    	
	    	<div class="row row2">
	    		<textarea class="first" name="jobcontent" placeholder="<?php echo $this->__('事業内容') ?>"></textarea>
	    		<textarea required class="last" name="jobdescription" placeholder="<?php echo $this->__('職務内容') ?>"></textarea>
	    	</div>
	    	
	    	<div class="row dashed-border"></div>
    		<p><?php echo $this->__('それ以前のご職歴がある場合は、こちらに全て入力してください。') ?></p>
	    	
	    	<div class="row row1">
	    		<textarea name="otherwork" placeholder="<?php echo $this->__('その他のご職歴') ?>"></textarea>
	    	</div>
    	</div>
    	
    	<div class="row heading">
    		<?php echo $this->__('言語能力') ?>
    	</div>
    	
    	<div class="row row2 lang">
    		<?php $langlevels = Mage::getModel('job/langlevel')->getCollection() ?>
    		<div class="first">
    			<label for="english"><?php echo $this->__('英語') ?></label>
	    		<select required id="english" name="english">
	    			<option value=""><?php echo $this->__('使用可能レベルを選択') ?></option>
	    			<?php foreach($langlevels as $level): ?>
	    			<option <?php echo ($data['english']== $level->getNameEn()) ? 'selected="selected"' : '' ?> value="<?php echo $level->getNameEn() ?>"><?php echo Mage::helper('job')->getTransName($level) ?></option>
	    			<?php endforeach; ?>
	    		</select>
    		</div>
    		<div class="last">
    			<label for="japanese"><?php echo $this->__('日本語') ?></label>
	    		<select required id="japanese" name="japanese">
	    			<option value=""><?php echo $this->__('使用可能レベルを選択') ?></option>
	    			<?php foreach($langlevels as $level): ?>
	    			<option <?php echo ($data['japanese']== $level->getNameEn()) ? 'selected="selected"' : '' ?> value="<?php echo $level->getNameEn() ?>"><?php echo Mage::helper('job')->getTransName($level) ?></option>
	    			<?php endforeach; ?>
	    		</select>
    		</div>
    	</div>
    	
    	<div class="row row1">
    		<textarea name="otherlang" placeholder="<?php echo $this->__('その他の言語能力がある場合は、こちらに言語の種類と使用可能レベルを記入してください。') ?>"></textarea>
    	</div>
    	
    	<div class="row heading">
    		<?php echo $this->__('希望条件・その他') ?>
    	</div>
    	
    	<div class="row row2">
    		<select multiple="multiple" id="category" class="first" name="category[]">
    			<option value=""><?php echo $this->__('希望業種') ?></option>
    			<?php echo $this->getCategoryList($data['category']) ?>
    		</select>
    		<script>
    			jQuery('#category').multipleSelect({
		            selectAll: false,
		            placeholder: '<?php echo $this->__('希望業種') ?>',
		        });
    		</script>
    		<select multiple="multiple" class="last" id="function" name="function[]">
    			<option value=""><?php echo $this->__('希望職種') ?></option>
    			<?php echo $this->getFunctionList($data['function']) ?>
    		</select>
    		<script>
    			jQuery('#function').multipleSelect({
		            selectAll: false,
		            placeholder: '<?php echo $this->__('希望職種') ?>',
		        });
    		</script>
    	</div>
    	
    	<div class="row row2">
    		<select multiple="multiple" id="expectedlevel" class="first" name="expectedlevel[]">
    			<option value=""><?php echo $this->__('希望職務レベル') ?></option>
    			<?php $joblevels = Mage::getModel('job/level')->getCollection() ?>
    			<?php foreach($joblevels as $level): ?>
    			<option <?php echo ($data['expectedlevel']== $level->getNameEn()) ? 'selected="selected"' : '' ?> value="<?php echo $level->getNameEn() ?>"><?php echo Mage::helper('job')->getTransName($level) ?></option>
    			<?php endforeach; ?>
    		</select>
    		<script>
    			jQuery('#expectedlevel').multipleSelect({
		            selectAll: false,
		            placeholder: '<?php echo $this->__('希望職務レベル') ?>',
		        });
    		</script>
    		<select multiple="multiple" class="last" id="expectedcountry" name="expectedcountry[]">
    			<option value=""><?php echo $this->__('希望勤務地') ?></option>
    			<?php $countrylist = Mage::getModel('job/country')->getCollection() ?>
    			<?php foreach($countrylist as $country): ?>
    			<option <?php echo ($data['expectedcountry']== $country->getNameEn()) ? 'selected="selected"' : '' ?> value="<?php echo $country->getNameEn() ?>"><?php echo Mage::helper('job')->getTransName($country) ?></option>
    			<?php endforeach; ?>
    		</select>
    		<script>
    			jQuery('#expectedcountry').multipleSelect({
		            selectAll: false,
		            placeholder: '<?php echo $this->__('希望勤務地') ?>',
		        });
    		</script>
    	</div>
    	
    	<div class="row row2">
    		<div class="first income">
	    		<input type="number" name="expectedsalary" placeholder="<?php echo $this->__('最低希望月収') ?>" />
	    		<?php echo $this->__('万円') ?>
    		</div>
    	</div>
    	
    	<div class="row row1">
    		<textarea name="requirements" placeholder="<?php echo $this->__('今後のキャリアイメージやご要望（職種、勤務地、他）等、ご自由にご入力ください。') ?>"></textarea>
    	</div>
    	
    	<div class="row heading">
    		<?php echo $this->__('自作の履歴書・職務経歴書のご用意がある方はこちらに添付してください。') ?>
    	</div>
    	
    	<div class="row row1">
    		<p>
    			<?php echo $this->__('Word, Excel, PowerPoint, PDF,Html,Textファイルがアップロード可能です。') ?>
    		</p>
    		<p>
    			<?php echo $this->__('1ファイルの容量は最大2MBまでとなっております') ?>。
    		</p>
    	</div>
    	
    	<div class="row">
    		<input id="fileupload" type="file" name="files[]" data-url="<?php echo Mage::getBaseUrl() ?>job/apply/upload" multiple>
			<div id="progress">
			    <div class="bar" style="width: 0%;"></div>
			</div>
			<div class="files">
				
			</div>
    	</div>
    	
    	<div class="row dashed-border"></div>
    	
    	<div class="row submit">
    		<button onclick="hook=false;" data-not="<?php echo $this->__('未入力の項目があります') ?>" data-checked="<?php echo $this->__('今すぐ登録する！') ?>" class="checkform checked btn button-blue button" type="submit" name="submit"><?php echo $this->__('今すぐ登録する！') ?></button>
    	</div>
    </form>
</div>
<script src="<?php echo Mage::helper('job')->getUrl() ?>js/fileupload/vendor/jquery.ui.widget.js"></script>
<script src="<?php echo Mage::helper('job')->getUrl() ?>js/fileupload/jquery.iframe-transport.js"></script>
<script src="<?php echo Mage::helper('job')->getUrl() ?>js/fileupload/jquery.fileupload.js"></script>
<script>
(function($){
	$(function () {
	    $('#fileupload').fileupload({
	        dataType: 'json',
	        progressall: function (e, data) {
		        var progress = parseInt(data.loaded / data.total * 100, 10);
		        $('#progress').show();
		        $('#progress .bar').text(progress + '%');
		        $('#progress .bar').css(
		            'width',
		            progress + '%'
		        );
		    },
	        done: function (e, data) {
	        	$('#progress').hide();
	            $.each(data.result.files, function (index, file) {
	            	if(!file.error){
	            		var btnText = '<?php echo $this->__('DELETE') ?>';
	            		var element = '<div class="file-uploaded clearfix"><a title="'+file.name+'" target="_blank" href="'+file.url+'" class="file-name fll">'+file.name+'</a><a href="#" class="flr delete">'+btnText+'</a>';
		            	element += '<input type="hidden" name="filenames[]" value="'+file.name+'" /></div>';
		            	$('.row .files').append(element);            	
		            	
					    $('a.delete').click(function(e){
					    	e.preventDefault();
					    	$(this).parent().fadeOut().remove();
					    });
	                }else{
	                	alert(file.error);
	                }
	            });
	        }
	    });
	    
	});
})(jQuery);
</script>
<script>
(function($){
	$(document).ready(function(){
		$('#numbercompany').on('change', function(){
			var divs = $('.company select:required, .company input:required, .company textarea:required, #workfunction');
			if($(this).val() == 0){
				divs.addClass('remove-required').removeAttr('required');
				divs.parent().find('.ms-parent').removeClass('required');
			}else{
				$('.remove-required').attr('required','required');
				$('.remove-required').parent().find('.ms-parent').addClass('required');
			}
		});
	});
})(jQuery);
</script>
<script>
	window.onbeforeunload = function(){
		if(hook){
			return 'Are you sure you want to leave?';
		}
	};
	(function($){
		$(document).ready(function(){
			
			$('input[type="radio"]').on('change', function(){
				if($('#check-for-working').is(':checked')){
					$('.row.workingtime .need-disable').attr('disabled','disabled');
					$('.row.workingtime p.small').css('display','inline-block');
				}else{
					$('.row.workingtime .need-disable').removeAttr('disabled');
					$('.row.workingtime p.small').hide();
				}
			});
		});
	})(jQuery)
</script>