<div id="request-recruitment">
	<h1><?php echo $this->__('人材紹介サービスに申し込む') ?></h1>
	<form id="request-form" action="" method="POST">
		<p><?php echo $this->__('＊＝必須') ?></p>
		<input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
		<input required type="text" name="company_name" placeholder="<?php echo $this->__('会社名') ?>" />
		<input required type="text" name="name" placeholder="<?php echo $this->__('担当者名') ?>" />
		<input required type="text" name="full_name" placeholder="<?php echo $this->__('担当者名（フリガナ）') ?>" />
		<input type="text" name="work_content" placeholder="<?php echo $this->__('事業内容') ?>" />
		<input type="text" name="address" placeholder="<?php echo $this->__('所在地') ?>" />
		<input type="number" name="phone" placeholder="<?php echo $this->__('電話番号') ?>" />
		<input required type="email" name="email" placeholder="<?php echo $this->__('メールアドレス') ?>" />
		<input required type="email" name="confirm_email" placeholder="<?php echo $this->__('メールアドレス（確認）') ?>" />
		<textarea required name="job_content" placeholder="<?php echo $this->__('求人内容の詳細をこちらにお書きください（募集職種、募集人数、職務内容、想定給与レンジ、勤務地等）。') ?>"></textarea>
		<div class="actions">
			<button type="submit" class="btn button-blue"><?php echo $this->__('送信') ?></button>
			<button onclick="resetForm();" class="btn button-grey"><?php echo $this->__('取消') ?></button>
		</div>
	</form>
</div>
<div id="phone-number">
	<div class="inline-b">
		<p><b><?php echo $this->__('ホーチミン本社') ?></b></p>
		<p class="number"><span class="tit"><?php echo $this->__('電話 ') ?>:</span> (84) - 8 - 3821 5122</p>
	</div>
	<div class="inline-b">
		<p><b><?php echo $this->__('ハノイオフィス') ?></b></p>
		<p class="number"><span class="tit"><?php echo $this->__('電話 ') ?>:</span> (84) - 4 - 3248 - 4446</p>
	</div>
	<div class="inline-b">
		<p><b><?php echo $this->__('ジャカルタオフィス') ?></b></p>
		<p class="number"><span class="tit"><?php echo $this->__('電話 ') ?>:</span> (62) - 21 290 22273</p>
	</div>
	<div class="inline-b">
		<p><b><?php echo $this->__('東京オフィス') ?></b></p>
		<p class="number"><span class="tit"><?php echo $this->__('電話 ') ?>:</span> (81) - 3 - 6222 5520</p>
	</div>
	<div class="inline-b">
		<p class="tit"><b><?php echo $this->__('メールアドレス ') ?>:</b></p>
		<p class="number"><a href="mailto:info@iconic-jp.com">info@iconic-jp.com</a></p>
	</div>
</div>