<div id="request-recruitment">
	<h1><?php echo $this->__('求人依頼申込') ?></h1>
	<form id="request-form" action="" method="POST">
		<input required type="text" name="name" placeholder="<?php echo $this->__('氏名') ?>" />
		<input required type="text" name="full_name" placeholder="<?php echo $this->__('氏名フリガナ') ?>" />
		<input required type="text" name="company_name" placeholder="<?php echo $this->__('会社名') ?>" />
		<input required type="text" name="work_content" placeholder="<?php echo $this->__('事業内容') ?>" />
		<input required type="number" name="phone" placeholder="<?php echo $this->__('電話番号') ?>" />
		<input type="text" name="guarantee" placeholder="<?php echo $this->__('担当者名') ?>" />
		<input required type="email" name="email" placeholder="<?php echo $this->__('メールアドレス') ?>" />
		<input required type="email" name="confirm_name" placeholder="<?php echo $this->__('確認（メールアドレス)') ?>" />
		<input type="text" name="address" placeholder="<?php echo $this->__('住所') ?>" />
		<textarea name="job_content" placeholder="<?php echo $this->__('求人内容') ?>"></textarea>
		<div class="actions">
			<button type="submit" class="btn button-blue"><?php echo $this->__('送信') ?></button>
			<button onclick="resetForm();" class="btn button-grey"><?php echo $this->__('取消') ?></button>
		</div>
	</form>
</div>
<div id="phone-number">
	<div class="inline-b">
		<p class="tit"><?php echo $this->__('電話 ') ?>:</p>
		<p><b><?php echo $this->__('ベトナム - 南部') ?></b></p>
		<p class="number">(84) - 8 - 3821 5122 / 5123 / 5124</p>
	</div>
	<div class="inline-b">
		<p><b><?php echo $this->__('ベトナム - 北部') ?></b></p>
		<p class="number">(84) - 4 - 3776 / 5963</p>
	</div>
	<div class="inline-b">
		<p><b><?php echo $this->__('インドネシア') ?></b></p>
		<p class="number">(62) - 21 290 22273 / 22274</p>
	</div>
	<div class="inline-b">
		<p><b><?php echo $this->__('東京 - 日本') ?></b></p>
		<p class="number">(81) - 3 - 6222 5520</p>
	</div>
	<div class="inline-b">
		<p class="tit"><b><?php echo $this->__('ウェブ ') ?>:</b></p>
		<p class="number"><a href="mailto:info@iconic-jp.com">info@iconic-jp.com</a></p>
	</div>
</div>
