<div class="success-page request">
	<h1><?php echo $this->__('ご依頼、ありがとうございました!') ?></h1>
	
	<p><?php echo $this->__('御社からの求人依頼は確かに送信されました。') ?></p>
	<p><?php echo $this->__('このページは<span id="countdown">5</span> 秒後自動的に戻ります。') ?></p>
</div>

<script type="text/javascript">
	(function () {
	    var timeLeft = 5,
	        cinterval;
	
	    var timeDec = function (){
	        timeLeft--;
	        document.getElementById('countdown').innerHTML = timeLeft;
	        if(timeLeft === 0){
	        	window.location = '/';
	            clearInterval(cinterval);
	        }
	    };
	
	    cinterval = setInterval(timeDec, 1000);
	})();
</script>
<!-- Google Code for Sign-up Conversion Page --> 
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 964610057;
var google_conversion_language = "en";
var google_conversion_format = "3";
var google_conversion_color = "ffffff";
var google_conversion_label = "J2StCJfosgkQiZD7ywM"; var google_remarketing_only = false;
/* ]]> */
</script>
<script type="text/javascript"  
src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt=""  
src="//www.googleadservices.com/pagead/conversion/964610057/?label=J2StCJfosgkQiZD7ywM&amp;guid=ON&amp;script=0"/>
</div>
</noscript>