<div id="search_results" class="clearfix">
	<div id="page-title" class="heading">
		<h2 class="blue-tit text-blue"><?php echo $this->__('検索結果') ?></h2>
	</div>
	<div class="info-search">
		<?php if($this->getKeyword()): ?>
		<div class="info inline-b">
			<?php echo $this->__('タイトル') ?>:
			<span><?php echo $this->getKeyword() ?></span>
		</div>
		<?php endif; ?>
		
		<?php if($this->hasCategory()): ?>
		<div class="info inline-b">
			<?php echo $this->__('国から探す') ?>:
			<span><?php echo Mage::helper('job')->getTransName(Mage::getModel('job/category')->load($this->getCategory())) ?></span>
		</div>
		<?php endif; ?>
		
		<?php if($this->hasLocation()): ?>
		<div class="info inline-b">
			<?php echo $this->__('国から探す') ?>:
			<?php $location = Mage::getModel('job/location')->load($this->getLocation());
				$country = Mage::getModel('job/country')->load($location->getCountryId());	
			?>
			<span><?php echo Mage::helper('job')->getTransName($country).'/'.Mage::helper('job')->getTransName($location) ?></span>
		</div>
		<?php endif; ?>
		
		<?php if($this->hasLanguage()): ?>
		<div class="info inline-b">
			<?php echo $this->__('国から探す') ?>:
			<span><?php echo Mage::helper('job')->getTransName(Mage::getModel('job/category')->load($this->getLanguage())) ?></span>
		</div>
		<?php endif; ?>
		
		<?php if($this->hasJobLevel()): ?>
		<div class="info inline-b">
			<?php echo $this->__('Đối tượng') ?>:
			<span><?php echo Mage::getModel('job/level')->load($this->getJobLevel())->getName() ?></span>
		</div>
		<?php endif; ?>		
		
		<?php if($this->hasIndustry()): ?>
		<div class="info inline-b">
			<?php echo $this->__('国から探す') ?>:
			<span><?php echo Mage::getModel('job/parentcategory')->load($this->getIndustry())->getName() ?></span>
		</div>
		<?php endif; ?>
		
		<?php if($this->hasFunction()): ?>
		<div class="info inline-b">
			<?php echo $this->__('業種') ?>:
			<span><?php echo Mage::getModel('job/parentcategory')->load($this->getFunction())->getName() ?></span>
		</div>
		<?php endif; ?>
		
		<?php if($this->hasFunctionCategory()): ?>
		<div class="info inline-b">
			<?php echo $this->__('業種') ?>:
			<span><?php echo Mage::getModel('job/category')->load($this->getFunctionCategory())->getName() ?></span>
		</div>
		<?php endif; ?>
		<p>
		</p>
	</div>
	<div class="results">
		<?php if($this->getResults()->count() > 0): ?>
			<script>
				jQuery(document).ready(function(){
					jQuery('.info-search > p').html(jQuery('.pager .amount'));
				});
			</script>
			<div class="content">
				<?php $col = $this->getResults()->setPageSize(12)->load(); ?>
			<?php foreach($col as $job): ?>
				<div class="job clearfix">
					<div class="job-wrapper">
						<p class="iconic-id">
							<?php echo $this->__('<b>No. %s</b>   |   登録日: %s', $job->getIconicId(), Mage::helper('job')->formatDate($job->getCreatedTime())) ?>
						</p>
						<p class="title">
							<?php if($this->getKeyword()): ?>
								<?php echo Mage::helper('job')->highlight($job->getTitle(), explode(' ',$this->getKeyword())) ?>
							<?php else: ?>
								<?php echo $job->getTitle() ?>
							<?php endif; ?>
						</p>
						<div class="job-details">
							<table>
								<tr>
									<td><b><?php echo $this->__('勤務地') ?>:</b> <?php echo $job->getWorkLocation() ?></td>
									<td><b><?php echo $this->__('国') ?>:</b> <?php echo $job->getCountry() ?></td>
									<td><b><?php echo $this->__('業種') ?>:</b> <?php echo $job->getFunctionName() ?></td>
									<td><b><?php echo $this->__('職種') ?>:</b> <?php echo $job->getCategoryName() ?></td>
								</tr>
								<tr>
									<td><b><?php echo $this->__('言語') ?>:</b> <?php echo $job->getLanguage() ?></td>
									<td>
										<table>
											<tr>
												<td><b><?php echo $this->__('レベル ') ?>:</b></td>
												<td><?php echo $job->getLevel() ?></td>
											</tr>
										</table>
									</td>
									<td><b><?php echo $this->__('給与') ?>:</b> <?php echo $job->getFullSalary() ?></td>
									<td><b><?php echo $this->__('採用定数') ?>:</b> <?php echo $job->getAmount() ?></td>
								</tr>
							</table>
						</div>
						<div class="actions">
							<a class="view" href="<?php echo $job->getUrl() ?>"><?php echo $this->__('詳細を見る') ?></a>
							<a class="apply" href="<?php echo $job->getApplyUrl() ?>"><?php echo $this->__('応募する') ?></a>
						</div>
					</div>
				</div>
			<?php endforeach; ?>
			</div>
			<?php
				echo $this->getPagerHtml();
			?>
		<?php else: ?>
			<div class="no-results clearfix">
				<img class="fll" src="<?php echo $this->getSkinUrl('images/no-results.png') ?>" alt="" />
				<span class="fll text"><?php echo $this->__('該当する条件の求人情報が見つかりませんでした。・検索条件を変えて再度求人検索してください。') ?></span>
			</div>
		<?php endif; ?>
	</div>
</div>
	<?php //if($this->hasFilters()): ?>
		<?php //foreach($this->getFilters() as $filter): ?>
			<?php //echo $filter->toHtml(); ?>
		<?php //endforeach; ?>
	<?php //endif; ?>