<form id="ajax-form">
	<?php foreach($this->getRequest()->getParams() as $key=>$value): ?>
	<input name="<?php echo $key ?>" type="hidden" value="<?php echo $value ?>" />
	<?php endforeach; ?>
	<input name="q" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getBlogSearch() ?>" />
	<input class="page" name="page" type="hidden" value="1" />
</form>
<div id="blog-page" class="clearfix">
	<div class="fll">
		<div id="blog-category">
			<?php echo $this->getChildHtml('category') ?>
		</div>
		<?php echo $this->getChildHtml('newest') ?>
	</div>
	<div class="blogs-wrap fll">
		<div id="blogs-content">
			
		</div>
		<div id="pager">
			
		</div>
	</div>
</div>