<div id="newest-blog">
	<!-- Tab Control -->
	<div id="blog-control" class="clearfix">
		<div data-tab="new" class="tab fll first new active">
			<span><?php echo $this->__('Newest') ?></span>
		</div>
		<div data-tab="popular" class="tab flr popular">
			<span><?php echo $this->__('Popular') ?></span>
		</div>
	</div>
	
	<!-- Tab Content -->
	<div id="blog-content">
		<!-- Content for category -->
		<div id="blog-tab-new" class="tab-content new">
			<ul>
				<?php foreach($this->getNewest() as $blog): ?>
					<?php $author = Mage::getModel('blog/author')->load($blog->getAuthorId()) ?>
				<li class="clearfix">
					<img class="fll" alt="" src="/media/resized/<?php echo $blog->getPhoto() ?>" />
					<div class="fll">
						<h6>
							<a href="<?php echo $blog->getUrl() ?>" title="<?php echo $blog->getTitle() ?>">
								<?php echo $blog->getTitle() ?>
							</a>
						</h6>
						<div class="inline date"><?php echo $blog->getDate() ?></div>
						|
						<div class="inline author"><a target="_blank" href="<?php echo $author->getLink() ?>"><?php echo $author->getName() ?></a></div>
						<br class="clear" />
						<?php 
						//get parent category list
						$parents = substr($blog->getCategoryId(), 1, -1);
						$parents = explode(',', $parents);
						$parentArr = array();
						foreach($parents as $catId){
							$catModel = Mage::getModel('blog/category')->load($catId);
							$parent = Mage::getModel('blog/parentcategory')->load($catModel->getParentcategoryId());
							if(!in_array($parent->getId(), $parentArr)){
								$parentArr[] = $parent->getId();
							}
						}
						?>
						<?php $i=1;foreach($parentArr as $parent): ?>
							<?php $parent = Mage::getModel('blog/parentcategory')->load($parent) ?>
							<a href="<?php echo $parent->getUrl() ?>" title="<?php echo Mage::helper('job')->getTransName($parent) ?>">
								<?php echo Mage::helper('job')->getTransName($parent) ?>
							</a>
							<?php echo ($i != count($parentArr)) ? '|' : '' ?>
						<?php $i++;endforeach; ?>
					</div>
				</li>
				<?php endforeach; ?>
			</ul>
		</div>
			
		<!-- Content for Function Tab -->
		<div style="display: none;" id="blog-tab-popular" class="tab-content popular">
			<ul>
				<?php foreach($this->getPopular() as $blog): ?>
					<?php $author = Mage::getModel('blog/author')->load($blog->getAuthorId()) ?>
				<li class="clearfix">
					<img class="fll" alt="" src="/media/resized/<?php echo $blog->getPhoto() ?>" />
					<div class="fll">
						<h6>
							<a href="<?php echo $blog->getUrl() ?>" title="<?php echo $blog->getTitle() ?>">
								<?php echo $blog->getTitle() ?>
							</a>
						</h6>
						<div class="inline date"><?php echo $blog->getDate() ?></div>
						|
						<div class="inline author"><a target="_blank" href="<?php echo $author->getLink() ?>"><?php echo $author->getName() ?></a></div>
						<br class="clear" />
						<?php 
						//get parent category list
						$parents = substr($blog->getCategoryId(), 1, -1);
						$parents = explode(',', $parents);
						$parentArr = array();
						foreach($parents as $catId){
							$catModel = Mage::getModel('blog/category')->load($catId);
							$parent = Mage::getModel('blog/parentcategory')->load($catModel->getParentcategoryId());
							if(!in_array($parent->getId(), $parentArr)){
								$parentArr[] = $parent->getId();
							}
						}
						?>
						<?php $i=1;foreach($parentArr as $parent): ?>
							<?php $parent = Mage::getModel('blog/parentcategory')->load($parent) ?>
							<a href="<?php echo $parent->getUrl() ?>" title="<?php echo Mage::helper('job')->getTransName($parent) ?>">
								<?php echo Mage::helper('job')->getTransName($parent) ?>
							</a>
							<?php echo ($i != count($parentArr)) ? '|' : '' ?>
						<?php $i++;endforeach; ?>
					</div>
				</li>
				<?php endforeach; ?>
			</ul>
		</div>
	</div>
</div>
<script>
(function($){
	$(document).ready(function(){
		$('#blog-control .tab').click(function(e){
			e.preventDefault();
			$('.tab').removeClass('active');
			$(this).addClass('active');
			$('.tab-content').fadeOut(200);
			$('.tab-content.'+$(this).data('tab')).fadeIn(200);
		});
	});
})(jQuery)
</script>